const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_EXECUTABLE,headless:true});const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));let fail=false,empty=false;
await p.route('**/functions/v1/gaming-radar**',r=>{if(fail)return r.fulfill({status:503,body:'{}'});const q=new URL(r.request().url()).searchParams,kind=q.get('kind'),page=Number(q.get('page')||1),date=(q.get('month')||'2026-09')+'-'+(q.get('day')||'15'),count=kind==='top250'?250:page===1?40:5;return r.fulfill({contentType:'application/json',body:JSON.stringify({items:empty?[]:Array.from({length:count},(_,i)=>({id:(page-1)*40+i+1,title:'Game '+((page-1)*40+i+1),url:'https://rawg.io/games/test-'+i,metacritic:99-Math.floor(i/10),releaseDate:date,platforms:['PC']})),total:empty?0:45,nextPage:!empty&&kind==='calendar'&&page===1?2:null,updatedAt:new Date().toISOString()})});});
const site='http://127.0.0.1:4175/shiyamsGamesList';
await p.goto(site+'/top250');await p.locator('.radar-card').first().waitFor();assert.equal(await p.locator('.radar-card').count(),40);
while(await p.locator('#library-more').isVisible())await p.locator('#library-more').click();assert.equal(await p.locator('.radar-card').count(),250);assert.equal(await p.locator('.radar-rank').last().textContent(),'250');
await p.locator('#top-search').fill('Game 250');assert.equal(await p.locator('.radar-card').count(),1);assert.equal(await p.locator('.radar-rank').textContent(),'250');
for(const route of ['top250','calendar']){await p.goto(site+'/'+route);await p.locator('.radar-card').first().waitFor();for(const width of [320,390,768,1024,1440]){await p.setViewportSize({width,height:1000});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),route+' overflow '+width);}assert.equal(await p.locator('header nav [aria-current]').textContent(),route==='top250'?'All-time top 250':'Release Calendar');}
assert.equal(await p.locator('#calendar-picker').isVisible(),false);assert.equal(await p.locator('[data-month]').count(),12);await p.locator('#calendar-year').fill('2028');await p.locator('#calendar-year').dispatchEvent('change');await p.locator('[data-month="02"]').click();await p.locator('#toggle-days').click();await p.waitForFunction(()=>document.querySelector('#library-heading').textContent.includes('2028'));assert.equal(await p.locator('[data-day]').count(),29);
await p.locator('[data-day="29"]').click();await p.waitForFunction(()=>document.querySelector('.calendar-date')?.textContent.includes('29'));assert.equal(await p.locator('#whole-month').isVisible(),true);await p.locator('#toggle-days').click();assert.equal(await p.locator('#calendar-picker').isVisible(),false);
await p.locator('#library-more').click();await p.waitForFunction(()=>document.querySelectorAll('.radar-card').length===45);assert.equal(await p.locator('#library-more').isVisible(),false);
await p.locator('#calendar-year').fill('2026');await p.locator('#calendar-year').dispatchEvent('change');await p.locator('[data-month="12"]').click();await p.locator('#next-year').click();assert.equal(await p.locator('#calendar-year').inputValue(),'2027');
for(const [id,value,key] of [['calendar-order','popular','order'],['calendar-platform','pc','platform']]){const request=p.waitForRequest(r=>r.url().includes('gaming-radar')&&new URL(r.url()).searchParams.get(key)===value);await p.locator('#'+id).selectOption(value);await request;}
const popularRequest=p.waitForRequest(r=>r.url().includes('gaming-radar')&&new URL(r.url()).searchParams.get('popular')==='1');await p.locator('#calendar-popular').check();await popularRequest;await p.waitForFunction(()=>document.querySelector('#library-panel').getAttribute('aria-busy')===null);
await p.emulateMedia({reducedMotion:'reduce'});await p.locator('[data-month="01"]').click();await p.waitForFunction(()=>document.querySelector('#library-panel').getAttribute('aria-busy')===null);assert.equal(await p.locator('#library-content').evaluate(e=>e.getAnimations().length),0);

fail=true;await p.locator('#library-refresh').click();await p.getByText('Showing saved data. Live updates are temporarily unavailable.').waitFor();await p.reload();await p.getByRole('heading',{name:'Game data is taking a break.'}).waitFor();fail=false;empty=true;await p.locator('#library-refresh').click();await p.getByRole('heading',{name:'No games listed.',exact:true}).waitFor();empty=false;await p.locator('#library-refresh').click();await p.locator('.radar-card').first().waitFor();assert.deepEqual(errors,[]);await b.close();console.log('PASS Top 250 full ranking/search, calendar leap day/month rollover/pagination, page links, five widths, error/stale/empty recovery.');})().catch(e=>{console.error(e);process.exit(1)});
