-- Run with the database owner, once. No credentials or initial user are embedded.
create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to anon, authenticated;

create table public.games (
  id bigint generated by default as identity primary key check (id > 0 and id <= 9007199254740991),
  title text not null check (length(btrim(title)) between 1 and 300),
  release_year integer check (release_year between 1000 and 9999),
  genres text[] not null check (cardinality(genres) between 1 and 30 and array_position(genres, null) is null),
  status text not null default 'unplayed' check (status in ('unplayed','loved','dropped','playing')),
  future boolean not null default false,
  poster text not null default '',
  video_id text not null default '' check (video_id = '' or video_id ~ '^[A-Za-z0-9_-]{11}$'),
  description text not null default '' check (length(description) <= 5000),
  rating_url text,
  poster_source text,
  video_channel text not null default '',
  video_source text,
  metacritic integer check (metacritic between 0 and 100),
  download_link text not null default '',
  metacritic_source text,
  metacritic_checked date,
  metacritic_platform text,
  description_source text,
  critic_video_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index games_title_year_unique on public.games (lower(btrim(title)), coalesce(release_year, 0));
create index games_status_idx on public.games(status);

create table public.admin_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  username text not null check (username ~ '^[A-Za-z0-9_ .-]{2,40}$'),
  role text not null default 'admin' check (role in ('super_admin','admin')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index admin_username_unique on public.admin_profiles(lower(username));
create unique index exactly_one_super_admin on public.admin_profiles ((role)) where role = 'super_admin';

create table public.activity_log (
  id bigint generated always as identity primary key,
  actor_id uuid,
  entity text not null,
  entity_id text not null,
  action text not null,
  label text not null,
  created_at timestamptz not null default now()
);

create function private.is_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.admin_profiles where id = auth.uid() and is_active);
$$;
create function private.is_super_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.admin_profiles where id = auth.uid() and is_active and role = 'super_admin');
$$;
revoke all on function private.is_admin(), private.is_super_admin() from public;
grant execute on function private.is_admin(), private.is_super_admin() to anon, authenticated;

alter table public.games enable row level security;
alter table public.admin_profiles enable row level security;
alter table public.activity_log enable row level security;
revoke all on public.games, public.admin_profiles, public.activity_log from anon, authenticated;
grant select on public.games to anon, authenticated;
grant insert, update, delete on public.games to authenticated;
grant usage on sequence public.games_id_seq to authenticated;
grant select on public.admin_profiles, public.activity_log to authenticated;
grant all on public.games, public.admin_profiles, public.activity_log to service_role;
grant usage, select on all sequences in schema public to service_role;
create policy games_public_read on public.games for select to anon, authenticated using (true);
create policy games_admin_insert on public.games for insert to authenticated with check (private.is_admin());
create policy games_admin_update on public.games for update to authenticated using (private.is_admin()) with check (private.is_admin());
create policy games_admin_delete on public.games for delete to authenticated using (private.is_admin());
create policy profiles_read on public.admin_profiles for select to authenticated using (id = auth.uid() or private.is_super_admin());
create policy activity_read on public.activity_log for select to authenticated using (private.is_admin());

create function private.touch_updated_at() returns trigger language plpgsql set search_path = '' as $$
begin new.updated_at = now(); return new; end;
$$;
create trigger games_updated before update on public.games for each row execute function private.touch_updated_at();
create trigger profiles_updated before update on public.admin_profiles for each row execute function private.touch_updated_at();

-- A partial unique index prevents a second super admin, including concurrent inserts.
-- These triggers prevent removing the only one after the explicit bootstrap.
create function private.protect_super_admin() returns trigger language plpgsql set search_path = '' as $$
begin
  if tg_op = 'DELETE' then
    if old.role = 'super_admin' then raise exception 'The super admin cannot be removed.' using errcode = '23514'; end if;
    return old;
  end if;
  if new.id <> old.id or new.role <> old.role then
    raise exception 'Admin identity and role are immutable.' using errcode = '23514';
  end if;
  if old.role = 'super_admin' and not new.is_active then
    raise exception 'The super admin must remain active.' using errcode = '23514';
  end if;
  return new;
end;
$$;
create trigger protect_super_admin before update or delete on public.admin_profiles
  for each row execute function private.protect_super_admin();
create function private.prevent_profile_truncate() returns trigger language plpgsql as $$
begin raise exception 'Admin profiles cannot be truncated.'; end;
$$;
create trigger prevent_profile_truncate before truncate on public.admin_profiles
  for each statement execute function private.prevent_profile_truncate();

create function private.sync_admin_email() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  update public.admin_profiles set email = new.email where id = new.id;
  return new;
end;
$$;
create trigger sync_admin_email after update of email on auth.users
  for each row when (old.email is distinct from new.email) execute function private.sync_admin_email();

create function private.audit_change() returns trigger language plpgsql security definer set search_path = '' as $$
declare record_data jsonb;
begin
  record_data = case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  insert into public.activity_log(actor_id, entity, entity_id, action, label)
    values(auth.uid(), tg_table_name, record_data->>'id', lower(tg_op),
      coalesce(record_data->>'title', record_data->>'username', ''));
  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$$;
create trigger games_audit after insert or update or delete on public.games
  for each row execute function private.audit_change();
create trigger admins_audit after insert or update or delete on public.admin_profiles
  for each row execute function private.audit_change();

create function public.update_my_username(new_username text) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not private.is_admin() then raise exception 'Access denied' using errcode = '42501'; end if;
  update public.admin_profiles set username = btrim(new_username) where id = auth.uid();
end;
$$;
create function public.manage_admin_profile(target_id uuid, new_username text, active boolean) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not private.is_super_admin() then raise exception 'Access denied' using errcode = '42501'; end if;
  if not exists(select 1 from public.admin_profiles where id = target_id and role = 'admin') then
    raise exception 'Select an ordinary admin account' using errcode = '23514';
  end if;
  update public.admin_profiles set username = btrim(new_username), is_active = active where id = target_id;
end;
$$;
create function public.set_currently_playing(game_ids bigint[]) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not private.is_admin() then raise exception 'Access denied' using errcode = '42501'; end if;
  if game_ids is null or array_position(game_ids, null) is not null then raise exception 'Invalid game selection'; end if;
  -- Lock the set for an atomic selection save; deselected active games return to backlog.
  lock table public.games in share row exclusive mode;
  if exists(select requested.game_id from unnest(game_ids) as requested(game_id) where not exists(select 1 from public.games g where g.id = requested.game_id)) then
    raise exception 'A selected game no longer exists' using errcode = '23514';
  end if;
  update public.games set status = 'unplayed' where status = 'playing' and not (id = any(game_ids));
  update public.games set status = 'playing' where id = any(game_ids) and status <> 'playing';
end;
$$;

-- These setup functions are unavailable to anon/authenticated, even via direct RPC calls.
create function public.bootstrap_super_admin(user_id uuid, display_name text) returns void
language plpgsql security definer set search_path = '' as $$
begin
  lock table public.admin_profiles in exclusive mode;
  if exists(select 1 from public.admin_profiles where role = 'super_admin') then
    raise exception 'Super admin already exists' using errcode = '23505';
  end if;
  insert into public.admin_profiles(id,email,username,role,is_active)
    select id,email,btrim(display_name),'super_admin',true from auth.users where id = user_id;
  if not found then raise exception 'Auth user does not exist'; end if;
end;
$$;
create function public.sync_games_sequence() returns void
language plpgsql security definer set search_path = '' as $$
begin
  lock table public.games in share row exclusive mode;
  perform setval('public.games_id_seq', greatest(coalesce((select max(id) from public.games),0),
    (select last_value from public.games_id_seq),1),true);
end;
$$;
revoke all on function public.update_my_username(text), public.manage_admin_profile(uuid,text,boolean),
  public.set_currently_playing(bigint[]), public.bootstrap_super_admin(uuid,text), public.sync_games_sequence() from public, anon, authenticated;
grant execute on function public.update_my_username(text), public.manage_admin_profile(uuid,text,boolean), public.set_currently_playing(bigint[]) to authenticated;
grant execute on function public.bootstrap_super_admin(uuid,text), public.sync_games_sequence() to service_role;
revoke all on all functions in schema private from public;

-- Realtime is an enhancement; focus/refresh also fetch fresh data.
do $$ begin
  if exists(select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table public.games;
  end if;
end $$;
